import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[cursor]
blink_interval = 500
thickness = 0.25

[cursor.style]
blinking = "Always"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.85

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 5
